support network neighbors
kubescape/node-agent pull request #141
Opened 2023-10-26 06:11 UTC by Daniel-GrunbergerCA

1. Add a network tracer to listen to communication.
2. Add a network manager to handle network events

2023-10-27 21:12 UTC, matthyx reviewed
integration in the node-agent LGTM, unfortunately I don't have enough time to validate the business logic of generating network-policies

2023-10-27 21:12 UTC, matthyx commented on pkg/networkmanager/network_event.go
> +	sort.Strings(keys)
;-)

2023-11-01 08:56 UTC, dwertent commented on go.mod
> +	github.com/kubescape/storage v0.0.30-0.20231024145442-963c4296f5b4
Can we release the storage?

2023-11-01 09:46 UTC, Daniel-GrunbergerCA commented on go.mod
> +	github.com/kubescape/storage v0.0.30-0.20231024145442-963c4296f5b4
waiting for vlad approval

2023-11-01 11:45 UTC, dwertent requested changes

2023-11-01 11:45 UTC, dwertent commented on pkg/storage/v1/storage_nocache.go
> +	kubeconfig := "/home/daniel/.kube/config"
```suggestion
	kubeconfig := "/home/daniel/.kube/config"
```

2023-11-01 11:45 UTC, dwertent commented on pkg/relevancymanager/v1/relevancy_manager.go
> +	// logger.L().Debug("fileList generated", helpers.String("container ID", containerID), helpers.String("k8s workload", watchedContainer.K8sContainerID), helpers.String("file list", fmt.Sprintf("%v",
Remove

2023-11-01 11:45 UTC, dwertent commented on pkg/networkmanager/network_manager.go
> +		logger.L().Info("NetworkManager - failed to get selector", helpers.String("reason", err.Error()), helpers.String("container ID", container.Runtime.ContainerID), helpers.String("k8s workload", k8sCo
Change log level

2023-11-01 11:45 UTC, dwertent commented on pkg/networkmanager/network_manager.go
> +		logger.L().Info("NetworkManager - selector is nil", helpers.String("container ID", container.Runtime.ContainerID), helpers.String("k8s workload", k8sContainerID))
Change log level

2023-11-01 11:45 UTC, dwertent commented on pkg/networkmanager/network_manager.go
> +			logger.L().Info("NetworkManager - failed to get network neighbor", helpers.String("reason", err.Error()), helpers.String("container ID", container.Runtime.ContainerID), helpers.String("k8s workloa
Change log level

2023-11-01 11:45 UTC, dwertent commented on pkg/networkmanager/network_manager.go
> +				logger.L().Info("NetworkManager - failed to create network neighbor", helpers.String("reason", err.Error()), helpers.String("container ID", container.Runtime.ContainerID), helpers.String("k8s wor
Change log level

2023-11-01 14:12 UTC, dwertent approved these changes

2023-11-01 14:20 UTC, merged