Feature/traceloop
kubescape/node-agent pull request #275
Opened 2024-04-24 12:16 UTC by amitschendel

## **User description**
## Overview

___

## **Type**
enhancement

___

## **Description**
- Removed the `RegisterPeekFunc` and integrated direct syscall event reporting across various components.
- Added `ReportSyscallEvent` method implementations in application profile manager and rule manager.
- Updated tests and mocks to align with the new syscall event reporting mechanism.
- Enhanced container watcher to handle syscall tracing and event propagation.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>applicationprofile_manager_interface.go</strong><dd><code>Interface Update: Add Syscall Reporting, Remove Peek Function</code></dd></summary>
<hr>

pkg/applicationprofilemanager/applicationprofile_manager_interface.go
<li>Removed <code>RegisterPeekFunc</code> method from the interface.<br> <li> Added <code>ReportSyscallEvent</code> method to the interface.<br>

</details>
    

  </td>
  <td><a href="https://github.com/kubescape/node-agent/pull/275/files#diff-c8a552f73130367e711a6bd1c8b00dbb9a7b1ab7d7274fc0db6be59f333afb51">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>applicationprofile_manager_mock.go</strong><dd><code>Mock Update: Add Syscall Event Reporting, Remove Peek Function</code></dd></summary>
<hr>

pkg/applicationprofilemanager/applicationprofile_manager_mock.go
<li>Removed mock implementation for <code>RegisterPeekFunc</code>.<br> <li> Added no-operation mock for <code>ReportSyscallEvent</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/kubescape/node-agent/pull/275/files#diff-ac635659b069359e3de4a50076026861cedfcfe02ac5ebc31176fb5cf49b506e">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>applicationprofile_manager.go</strong><dd><code>Application Profile Manager: Integrate Syscall Event Handling</code></dd></summary>
<hr>

pkg/applicationprofilemanager/v1/applicationprofile_manager.go
<li>Removed <code>syscallPeekFunc</code> and associated logic.<br> <li> Added handling for syscall events in <code>ReportSyscallEvent</code>.<br> <li> Updated <code>saveProfile</code> to handle new syscall event logic.<br>

</details>
    

  </td>
  <td><a href="https://github.com/kubescape/node-agent/pull/275/files#diff-fc815317651e17975c117749e7661127dbcde82fd9d4d36ebc76cb5b09b3c54e">+22/-16</a>&nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>container_watcher.go</strong><dd><code>Container Watcher: Add Syscall Tracing Integration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/containerwatcher/v1/container_watcher.go
<li>Added <code>tracersyscalls</code> import and related syscall tracing logic.<br> <li> Integrated syscall event handling in container watcher setup.<br>

</details>
    

  </td>
  <td><a href="https://github.com/kubescape/node-agent/pull/275/files#diff-9fa1df18c7f441eb315fcce4daa355a4517ee2d692d1b6a572f93ee5edbd247d">+29/-7</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>container_watcher_private.go</strong><dd><code>Container Watcher Private: Manage Syscall Tracer Lifecycle</code></dd></summary>
<hr>

pkg/containerwatcher/v1/container_watcher_private.go
- Added logic to attach/detach syscall tracer to containers.

</details>
    

  </td>
  <td><a href="https://github.com/kubescape/node-agent/pull/275/files#diff-6f95b4caa6090a17da5aed1923600fd049392d228e0fba99cc212f48111f3ffe">+37/-10</a>&nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>syscall.go</strong><dd><code>Implement Syscall Tracing and Event Handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/containerwatcher/v1/syscall.go
- Implemented syscall tracing setup and event handling.

</details>
    

  </td>
  <td><a href="https://github.com/kubescape/node-agent/pull/275/files#diff-198ba4cfa9ac9767d0a4b7c1f84717cdc8728e8e868e980db5e456562a322be9">+32/-8</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>rule_manager.go</strong><dd><code>Rule Manager: Implement Syscall Event Reporting</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/rulemanager/v1/rule_manager.go
<li>Added <code>ReportSyscallEvent</code> method implementation.<br> <li> Removed unused <code>RegisterPeekFunc</code>.<br> <li> Updated other event reporting methods to use <code>waitForRuleBindings</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/kubescape/node-agent/pull/275/files#diff-256c2d268cc7600c33337b908014ecfeb9f05e4ff302df5627aff93079a982a6">+60/-112</a></td>
</tr>                    
</table></td></tr><tr><td><strong>Tests
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>applicationprofile_manager_test.go</strong><dd><code>Update Tests for Application Profile Manager</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pkg/applicationprofilemanager/v1/applicationprofile_manager_test.go
<li>Updated tests to use <code>ReportSyscallEvent</code> instead of <code>RegisterPeekFunc</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/kubescape/node-agent/pull/275/files#diff-4e4af04b3ed98cb9feaf13f1406a7d71609ab637ea5cb47c4f749cfb240afca1">+3/-4</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

2024-04-25 08:12 UTC, dwertent requested changes

2024-04-25 08:12 UTC, dwertent commented on pkg/containerwatcher/v1/container_watcher_private.go
> +						logger.L().Error("reading syscall tracer", helpers.String("error", err.Error()))
```suggestion
						logger.L().Debug("reading syscall tracer", helpers.String("error", err.Error()))
```

2024-04-25 12:01 UTC, amitschendel commented on pkg/containerwatcher/v1/container_watcher_private.go
> +						logger.L().Error("reading syscall tracer", helpers.String("error", err.Error()))
done

2024-05-28 12:05 UTC, dwertent approved these changes

2024-05-28 12:11 UTC, merged