Feature/ptrace
kubescape/node-agent pull request #381
Opened 2024-09-30 15:18 UTC by afek854

## Overview

2024-10-07 14:26 UTC, amitschendel requested changes

2024-10-07 14:26 UTC, amitschendel commented on pkg/containerwatcher/v1/container_watcher_private.go
> +			return err
Why return err and not join?

2024-10-07 14:26 UTC, amitschendel commented on pkg/containerwatcher/v1/container_watcher_private.go
> +			return err
Same as above

2024-10-07 14:26 UTC, amitschendel commented on pkg/containerwatcher/v1/ptrace.go
> +	if event.Type == types.DEBUG {
Check using this:
`if event.Type != types.NORMAL {`

2024-10-07 14:26 UTC, amitschendel commented on pkg/containerwatcher/v1/ptrace.go
> +	// Stop open tracer
It's not the open tracer ;)

2024-10-07 14:26 UTC, amitschendel commented on pkg/containerwatcher/v1/ptrace.go
> +	ch.openTracer.Stop()
Please don't stop the open tracer but the ptrace.

2024-10-07 14:26 UTC, amitschendel commented on pkg/ebpf/gadgets/ptrace/tracer/bpf/ptrace_detector.h
> +struct syscalls_enter_ptrace_args {
Why not using the vmlinux struct?

2024-10-07 14:26 UTC, amitschendel commented on pkg/ruleengine/v1/factory.go
> +			R1015MaliciousPtraceUsageRuleDescriptor,
What happened to R1014?

2024-10-07 14:26 UTC, amitschendel commented on pkg/ruleengine/v1/r1015_malicious_ptrace_usage.go
> +		allowedProcesses: []string{"processA", "processB"}, // Example allowed processes
Delete example

2024-10-07 14:26 UTC, amitschendel commented on pkg/ruleengine/v1/r1015_malicious_ptrace_usage.go
> +	allowedProcesses []string
Use mapset to support a couple of goroutines

2024-10-07 14:42 UTC, afek854 commented on pkg/containerwatcher/v1/container_watcher_private.go
> +			return err
DONE

2024-10-07 14:42 UTC, afek854 commented on pkg/containerwatcher/v1/container_watcher_private.go
> +			return err
DONE

2024-10-08 10:47 UTC, amitschendel approved these changes

2024-10-08 11:42 UTC, merged