Feature/thirdparty enricher
kubescape/node-agent pull request #396
Opened 2024-10-31 12:05 UTC by afek854

## Overview

2024-11-04 12:35 UTC, afek854 commented
Blocked until IG

2024-11-20 15:03 UTC, afek854 commented
We're using inspektor gadget by commit hash until new release

2024-11-21 13:18 UTC, afek854 commented on pkg/containerwatcher/v1/container_watcher.go
> +		ruleManager.ReportEvent(utils.ExecveEventType, &event)
It does not matter

2024-11-21 13:34 UTC, matthyx commented on pkg/ebpf/gadgets/hardlink/tracer/hardlink_bpfel.go
> +	_          [3]byte
padding?

2024-11-21 13:40 UTC, matthyx commented on pkg/malwaremanager/v1/malware_manager.go
> +		mm.reportFileOpen(&open.Event)
do you really have to dereference here?

2024-11-21 13:46 UTC, matthyx approved these changes

2024-12-02 07:55 UTC, amitschendel requested changes

2024-12-03 08:14 UTC, merged